/**
 * Thin renderers over the canonical brief model (brief/model.js).
 * renderText  → on-screen implementation plan (BriefCard).
 * renderMarkdown → full downloadable brief (export).
 */

export function renderText(brief) {
  if (!brief) return '';

  const L = [
    'IMPLEMENTATION PLAN',
    '===================',
    '',
    `Project: ${brief.header?.project || '—'}`,
    `Owner:   ${brief.header?.owner || 'the builder'}`,
    '',
    ...(brief.story
      ? ['── Story ──────────────────────────────────────────', ...brief.story.split('\n').map(s => `  ${s}`), '']
      : []),
    '── Context ──────────────────────────────────────',
    ...(brief.context || []).map(c => `  ${(c.label || '').padEnd(17)}: ${c.body}`),
    '',
    '── Suggested next steps ─────────────────────────',
    ...(brief.nextSteps || []).map((s, i) => `  ${i + 1}. ${s}`),
    '',
    '── MVP scope guidance ───────────────────────────',
    ...(brief.mvpGuidance || []).map(s => `  • ${s}`),
    '',
    ...(brief.footer || []).map(s => `> ${s}`),
  ];
  return L.join('\n');
}

/** Pull the rendered text out of a section value that may be string or { text }. */
function pickText(v) {
  if (v == null) return null;
  return typeof v === 'object' ? v.text : v;
}

/**
 * Full markdown export. Uses the canonical model for the header/overview and
 * the per-stage section texts for the body — both new and legacy records work.
 */
export function renderMarkdown(brief, record) {
  const outputs = record?.outputs || {};
  const time = record?.time || new Date().toLocaleString();

  const L = [
    `# ${brief?.ownerName || 'Project'} — AbridgeAI Project Brief`,
    '',
    `> Generated by AbridgeAI · ${time}`,
    '',
    '## Project Overview',
    '',
    `- **Idea:** ${brief?.idea || '—'}`,
    `- **Stack:** ${brief?.stackLabel || '—'}`,
    `- **Type:** ${brief?.projectType || '—'}`,
    `- **Team:** ${brief?.teamSize || '—'}`,
    `- **Audience:** ${brief?.audience || '—'}`,
    `- **GitHub:** ${brief?.github || '—'}`,
    `- **Deadline:** ${brief?.deadline || '—'}`,
    `- **Comfort level:** ${brief?.comfort || '—'}`,
    '',
  ];

  const sections = [
    ['1. Builder Signals (GitHub Analysis)', pickText(outputs.github)],
    ['2. Research & Opportunity Analysis',   pickText(outputs.research)],
    ['3. Feasibility Assessment',            pickText(outputs.feasibility)],
    ['4. Architecture Direction',            pickText(outputs.architecture)],
    ['5. Tech Stack Recommendation',         pickText(outputs.stack)],
    ['6. Builder Plan & Starter Scaffold',   pickText(outputs.builder)],
    ['7. Implementation Plan',               pickText(outputs.brief)],
  ];

  sections.forEach(([title, body]) => {
    if (!body) return;
    L.push(`## ${title}`, '', '```text', body, '```', '');
  });

  return L.join('\n');
}